{% set name = "wagtail-color-panel" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail-color-panel-{{ version }}.tar.gz
  sha256: 93823850e6afbcd364d9e02e2feb952fcebaeda03fa45053a47546a067eb852d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pytest-runner
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=4.1

test:
  imports:
    - wagtail_color_panel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marteinn/wagtail-color-panel
  summary: A package that adds new panels for selecting colors, works both on regular page fields and stream field.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
