{% set name = "wagtail-color-panel" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2349daa24ad9ef78685be493bc4f30a325383a1fcea01506232ba35048849f6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pytest-runner
    - pip
    - setuptools
  run:
    - django
    - python >={{ python_min }}
    - wagtail >=5.2

test:
  imports:
    - wagtail_color_panel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marteinn/wagtail-color-panel
  summary: A package that adds new panels for selecting colors, works both on regular page fields and stream field.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
